version: "2.1"
services:
  web:
    build:
        context: .
        dockerfile: docker/nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/var/www
    links:
      - php
    depends_on:
      - php
  php:
    build:
        context: .
        dockerfile: docker/php/Dockerfile
    volumes:
      - ./app:/var/www

